In [1]:
import numpy as np

=>it uses array or matrix as raw data 

In [3]:
l=[123,45,23,43,56]

a= np.array(l)
print(a)
print(type(a))

[123  45  23  43  56]
<class 'numpy.ndarray'>


In [6]:
a= np.asarray(l)
print(a)
print(type(a))

[123  45  23  43  56]
<class 'numpy.ndarray'>


In [14]:
a= np.asanyarray(l)
print(a)
print(type(a))

[123  45  23  43  56]
<class 'numpy.ndarray'>


In [15]:

b=a #--------------reference-----------------'sollow copy'
c = np.copy(a) #-------makes another copy----'deep copy'

print("a", a)
print("b", b)
print("c", c)

a [123  45  23  43  56]
b [123  45  23  43  56]
c [123  45  23  43  56]


In [16]:
a[2]=10000
print("a", a)
print("b", b)
print("c", c)

a [  123    45 10000    43    56]
b [  123    45 10000    43    56]
c [123  45  23  43  56]


In [17]:
# functions to create different types of array

np.fromfunction(lambda i, j : i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [18]:
np.fromfunction(lambda i, j : i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [23]:
ite = [i*i for i in range(5) ]

# to create array from iterable data
np.fromiter(ite,float)

array([ 0.,  1.,  4.,  9., 16.])

In [27]:
# from string
np.fromstring("123 345 678", sep =" ")

array([123., 345., 678.])

<!-- Numpy datatypes  -->

In [28]:
l=[2,3,4,5,6,7]
ar= np.array(l)
l

[2, 3, 4, 5, 6, 7]

In [29]:
# to find dimension of array 
ar.ndim

1

In [34]:
ar2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar2)
print("++++ ",ar2.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
++++  2


In [35]:
# to get size
print(ar.size)
print(ar2.size)

6
9


In [36]:
# to get shape
print(ar.shape)
print(ar2.shape)

(6,)
(3, 3)


In [40]:


# range takes only int values as start stop jump
# Numpy allows to give in floating points
# list(np.arange(2.3,6.8,.5))------------------can convert it into list also
np.arange(2.3,6.8,.5)

array([2.3, 2.8, 3.3, 3.8, 4.3, 4.8, 5.3, 5.8, 6.3])

In [44]:

# linspace (start, end, n)
# it creates array with n data b/w start and end with equal interval [including start , end]

np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [51]:
# it uses log to divide -normally base10
np.logspace(10,100,10, base=2)

array([1.02400000e+03, 1.04857600e+06, 1.07374182e+09, 1.09951163e+12,
       1.12589991e+15, 1.15292150e+18, 1.18059162e+21, 1.20892582e+24,
       1.23794004e+27, 1.26765060e+30])

In [45]:
# to create array of zeros of shape --> np.zeros(shape)
np.zeros(3)

array([0., 0., 0.])

In [47]:
# to create array of 1 of shape --> np.ones(shape)
x = np.ones((3,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [48]:
x+ 9

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [49]:
# creates identity mat
# identity mat ------square--diag=1
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [52]:
# random 
np.random.randn(3,4)   # generate data such that mean=0 std=1

array([[-1.64415149,  0.98748605, -0.6564554 ,  0.32483594],
       [-0.82866789,  1.59490685,  0.69428021,  0.61298917],
       [ 0.08471153,  1.47674814, -0.5255423 , -0.4359141 ]])

In [53]:
np.random.rand(3,4)   

array([[0.92379487, 0.46144786, 0.50684433, 0.7999575 ],
       [0.43382924, 0.74075506, 0.07377957, 0.81085342],
       [0.09220882, 0.76010109, 0.37215622, 0.80158187]])

In [57]:
# randint(low, high=None, size=None, dtype=int)

ar2=np.random.randint(1,10,(4,3), int )
ar2

array([[9, 3, 1],
       [7, 7, 9],
       [5, 3, 8],
       [1, 1, 9]])

In [61]:
# using same data we can re shape  but n*m shoud be equal
#  if we want to give only one dimension  we can kernel will accordingly
#  consider next dimension just provide that dimensionin in any negative
ar2.reshape((6,-1))

array([[9, 3],
       [1, 7],
       [7, 9],
       [5, 3],
       [8, 1],
       [1, 9]])

In [63]:

# can retrive data based on location---[row][col]
ar2[2][1]

3

In [69]:
# can give range/list also
ar2[1:4, 1:3]

array([[7, 9],
       [3, 8],
       [1, 9]])

In [71]:
ar = np.random.randint(1,100,(5,5))
ar

array([[96,  1, 39, 89, 89],
       [20, 38, 58, 66, 92],
       [28, 61, 28, 77, 52],
       [50, 45, 88, 21,  2],
       [71, 59, 46, 64, 11]])

In [74]:
# Q find elem greater than 50
ar[ar >50]

array([96, 89, 89, 58, 66, 92, 61, 77, 52, 88, 71, 59, 64])

In [75]:
# can easily manipulate
ar[0][0]=999

In [76]:
ar

array([[999,   1,  39,  89,  89],
       [ 20,  38,  58,  66,  92],
       [ 28,  61,  28,  77,  52],
       [ 50,  45,  88,  21,   2],
       [ 71,  59,  46,  64,  11]])



            In-built function

In [77]:
arr1= np.random.randint(1,3, (3,3))
arr2= np.random.randint(1,3, (3,3))

In [78]:
arr1

array([[2, 2, 2],
       [2, 1, 2],
       [1, 1, 1]])

In [79]:
arr2

array([[2, 2, 2],
       [2, 2, 2],
       [2, 1, 1]])

In [80]:
arr1+arr2

array([[4, 4, 4],
       [4, 3, 4],
       [3, 2, 2]])

In [81]:
arr1/arr2

array([[1. , 1. , 1. ],
       [1. , 0.5, 1. ],
       [0.5, 1. , 1. ]])

In [84]:
# not an matrix multiplication 
# it is an index multiplication
arr1*arr2

array([[4, 4, 4],
       [4, 2, 4],
       [2, 1, 1]])

In [86]:
# matrix multiplication 
arr1@arr2

array([[12, 10, 10],
       [10,  8,  8],
       [ 6,  5,  5]])

In [87]:

# in mumpy divide by zero is infinity doest give error
arr1/0

C:\Users\asus\AppData\Local\Temp\ipykernel_6368\1265251489.py:2: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [88]:
# can perform any operation
arr1**2

array([[4, 4, 4],
       [4, 1, 4],
       [1, 1, 1]])


                Numpy broadcasting
          

In [95]:
arr = np.zeros((4,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [106]:
row =np.array([1,2,3,4])
print(row)
print(row.shape)

[1 2 3 4]
(4,)


In [104]:
# above when we where adding 100 it was added to each  an every an element but
# now we passed an row mat it added row wise this is known as broadcasting 
arr +row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [112]:
# can perform broadcasting col wise to by providing clo mat

# can't get transope of 1D that's why generating 2D and transposing---->bcoz default creates row mat 
col= np.array([[1,2,3,4]]).T
print(col)
print(col.shape)

[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [113]:
arr +col

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [114]:
arr= np.random.randint(1,4,(3,4))

In [115]:
arr

array([[3, 1, 1, 3],
       [3, 2, 1, 3],
       [1, 1, 1, 3]])

In [116]:
# to find sqrt
np.sqrt(arr)

array([[1.73205081, 1.        , 1.        , 1.73205081],
       [1.73205081, 1.41421356, 1.        , 1.73205081],
       [1.        , 1.        , 1.        , 1.73205081]])

In [117]:
np.exp(arr)

array([[20.08553692,  2.71828183,  2.71828183, 20.08553692],
       [20.08553692,  7.3890561 ,  2.71828183, 20.08553692],
       [ 2.71828183,  2.71828183,  2.71828183, 20.08553692]])

In [119]:
# np.log(arr)
np.log10(arr)

array([[0.47712125, 0.        , 0.        , 0.47712125],
       [0.47712125, 0.30103   , 0.        , 0.47712125],
       [0.        , 0.        , 0.        , 0.47712125]])



                            Numpy 2
                            

In [120]:
# manipulation
arr = np.random.randint(1,10,(3,4))

In [125]:
arr

array([[2, 7, 4, 1],
       [7, 2, 2, 8],
       [7, 5, 3, 3]])

In [126]:
# arr 2D ---> arr1D
arr.flatten()

array([2, 7, 4, 1, 7, 2, 2, 8, 7, 5, 3, 3])

In [132]:
# to increase dimensions dynamically we 
arr1=np.array([1,2,3,4])
x = np.expand_dims(arr1, axis=1)
x

array([[1],
       [2],
       [3],
       [4]])

In [133]:
np.expand_dims(arr1, axis=0)

array([[1, 2, 3, 4]])

In [137]:
# to decrease dimensions dynamically we 

y = np.squeeze(x)
y

array([1, 2, 3, 4])

In [138]:
# to change the place on rolling postion
np.roll(y, 2)
# it will shif each element to two position ahead 1[at 0]---1[ at 0+2=2]

array([3, 4, 1, 2])

In [139]:

# creates diagonal mat using list
np.diag(y)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

            
            
                Binary operation(+,-,*,/,%,~,&,|,<....................)

In [145]:
arr1= np.random.randint(1, 10,(3,4))
arr2= np.random.randint(1, 10,(3,4))

print(arr1)
print("=================")
print(arr2)

[[5 6 7 1]
 [2 1 3 3]
 [8 2 4 9]]
[[3 9 6 3]
 [5 2 1 3]
 [1 8 6 9]]


In [146]:
#  arr1{op}arr2
# ex
arr1%arr2

array([[2, 6, 1, 1],
       [2, 1, 0, 0],
       [0, 2, 4, 0]])

In [147]:
arr1&arr2

array([[1, 0, 6, 1],
       [0, 0, 1, 3],
       [0, 0, 4, 9]])

In [148]:
~arr1

array([[ -6,  -7,  -8,  -2],
       [ -3,  -2,  -4,  -4],
       [ -9,  -3,  -5, -10]])



            String function
            

In [151]:
arr= np.array(["nm","pn","tp"])

In [152]:
arr

array(['nm', 'pn', 'tp'], dtype='<U2')

In [153]:
# to convert all elem to upper
np.char.upper(arr)

array(['NM', 'PN', 'TP'], dtype='<U2')

In [154]:
np.char.title(arr)

array(['Nm', 'Pn', 'Tp'], dtype='<U2')

In [156]:
np.char.capitalize(arr)

array(['Nm', 'Pn', 'Tp'], dtype='<U2')


            Mathematical func


In [157]:
arr1

array([[5, 6, 7, 1],
       [2, 1, 3, 3],
       [8, 2, 4, 9]])

In [159]:
# cos tan tanh exp sqrt log log10 .....
np.sin(arr1)

array([[-0.95892427, -0.2794155 ,  0.6569866 ,  0.84147098],
       [ 0.90929743,  0.84147098,  0.14112001,  0.14112001],
       [ 0.98935825,  0.90929743, -0.7568025 ,  0.41211849]])

In [160]:
np.power(arr1, 3)

array([[125, 216, 343,   1],
       [  8,   1,  27,  27],
       [512,   8,  64, 729]], dtype=int32)

In [162]:
# mean median std var max min
np.mean(arr1)

4.25

                                      
                                      Part 3
                                      

In [163]:
# sort search counting func

In [164]:
arr = np.array([3,5,6,7,3,5,6,7,93,3,3,4,5])

In [165]:
arr

array([ 3,  5,  6,  7,  3,  5,  6,  7, 93,  3,  3,  4,  5])

In [166]:
np.sort(arr)

array([ 3,  3,  3,  3,  4,  5,  5,  5,  6,  6,  7,  7, 93])

In [167]:
# return the index were data will be stored 
np.searchsorted(arr, 89)

13

In [170]:
# to find no.of non zero val
arr1 =np.array([0,34,0,4,0,0,0,3])
np.count_nonzero(arr1)

3

In [174]:
# to find index of elements which statisfies cond
# in short filtering which returns index
print('arr--',arr)
np.where(arr>5)

arr-- [ 3  5  6  7  3  5  6  7 93  3  3  4  5]


(array([2, 3, 6, 7, 8], dtype=int64),)

In [177]:
np.extract(arr>10,arr)

array([93])

In [178]:
arr

array([ 3,  5,  6,  7,  3,  5,  6,  7, 93,  3,  3,  4,  5])

In [ ]:



# byte swapping

In [179]:
arr.byteswap()

array([  50331648,   83886080,  100663296,  117440512,   50331648,
         83886080,  100663296,  117440512, 1560281088,   50331648,
         50331648,   67108864,   83886080])

In [180]:


# copies & views

In [182]:
# Deep copy------------------- makes another copy,  both will point to different obj
a = np.copy(arr)

In [184]:
# sollow copy------------------- doesn't makes another copy,  both will point to same obj 
# b= arr is same
b= arr.view()

In [186]:
print("arr-",arr)
print("a---",a)
print("b---",b)

arr- [ 3  5  6  7  3  5  6  7 93  3  3  4  5]
a--- [ 3  5  6  7  3  5  6  7 93  3  3  4  5]
b--- [ 3  5  6  7  3  5  6  7 93  3  3  4  5]


In [188]:
a[0]=99
b[0]=11
print("arr-",arr)
print("a---",a)
print("b---",b)

arr- [11  5  6  7  3  5  6  7 93  3  3  4  5]
a--- [99  5  6  7  3  5  6  7 93  3  3  4  5]
b--- [11  5  6  7  3  5  6  7 93  3  3  4  5]


In [189]:


# for matrix operation matlib libray is present in Numpy

In [190]:
import numpy.matlib as nm

In [194]:
nm.eye(3)

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [195]:



# linear algebra

In [196]:
arr1 = np.random.randint([[2,3],[4,5]])
arr2 = np.random.randint([[5,3],[2,5]])

In [197]:
# returns dot product
np.dot(arr1,arr2)

array([[4, 2],
       [5, 4]])

In [198]:
arr1@arr2

array([[4, 2],
       [5, 4]])

In [199]:
np.count_nonzero(arr)

13